---
- hosts: all
  become: true
  tasks:

    - name: Remove apache and php packages
      package:
        name: 
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
        state: absent
        update_cache: yes
