---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "(Ubuntu)" 

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php packages
      tags: apache,php
      package:
        name: 
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
        state: latest
        update_cache: yes

- hosts: db_servers
  become: true
  tasks:
    - name: install maria db server package
      tags: mariadb
      package:
        name: mariadb-server
        state: latest
        update_cache: yes

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
        update_cache: yes
